name: Docker Build and Deploy

on:
  push:
    branches:
      - master  # Executa o workflow em push para o branch principal
  pull_request:
    branches:
      - master  # Executa o workflow em pull requests

jobs:
  build:
    runs-on: ubuntu-latest  # Define que o job será executado em um container Ubuntu
    steps:
      - name: Check out the code
        uses: actions/checkout@v2  # Faz checkout do código para o ambiente do GitHub Actions

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Configura o Buildx (se precisar do BuildKit)

      - name: Build Docker image
        run: |
          docker build -t f5sites-angular .  # Substitua "my-app" com o nome desejado para sua imagem
          
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Nome de usuário do Docker Hub
          password: ${{ secrets.DOCKER_PASSWORD }}  # Senha do Docker Hub

      - name: Push Docker image to Docker Hub
        run: |
          docker push f5sites/f5sites-angular:latest  # Envia a imagem para o Docker Hub

      - name: Deploy (opcional)
        run: |
          echo "Aqui você pode adicionar o comando para deploy, como o docker-compose ou kubectl"

